MySites/Controllers/AdminHomeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace MySites.Controllers
{
    [Authorize(Roles = "Admin")]
    public class AdminHomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

MySites/Controllers/EducationController.cs
using Entities.Entity.Concrete;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Service.Services.Abstract;
using System.Data;

namespace MySites.Controllers
{
    [Authorize(Roles = "Admin")]
    public class EducationController : Controller
    {
        private readonly IEducationsService _educationsService;

        public EducationController(IEducationsService educationsService)
        {
            _educationsService = educationsService;
        }

        public IActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> EducationEkle(Educations educations)
        {
            await _educationsService.CreateAsync(educations);
            return RedirectToAction("Index");
        }
        [HttpPost]
        public async Task<IActionResult> EducationGuncelle(Educations educations)
        {
            await _educationsService.UpdateAsync(educations);
            return RedirectToAction("Index");
        }
        [HttpPost]
        public async Task<IActionResult> EducationSil(int id)
        {
            await _educationsService.DeleteAsync(id);
            return RedirectToAction("Index");
        }
        [HttpGet]
        public async Task<IActionResult> EducationGetAll()
        {
            var educationData = await _educationsService.GetAllAsync();
            return Json(new { data = educationData });
        }
    }
}

MySites/Controllers/LayoutController.cs
using Microsoft.AspNetCore.Mvc;
using Service.Services.Abstract;

namespace MySites.Controllers
{
    public class LayoutController : Controller
    {
        private readonly IPersonalDataService _personalDataService;

        public LayoutController( IPersonalDataService personalDataService)
        {
            _personalDataService = personalDataService;
        }
        [HttpGet]
        public  IActionResult _Layout()
        {
            return View();
        }
        [HttpGet]
        public async Task<IActionResult> PersonalDataGetAll()
        {
            var personalData = await _personalDataService.GetAllAsync();
            return Json(personalData);
        }
    }
}

MySites/Controllers/LoginController.cs
using Core.Manager;
using Entities.Entity.Concrete;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MySites.Extensions;

namespace MySites.Controllers
{
    [AllowAnonymous]
    public class LoginController : Controller
    {
        private readonly IAccessManager _accessManager;
        private readonly IClaimsManager _claimsManager;
        public LoginController(IAccessManager accessManager, IClaimsManager claimsManager)
        {
            _accessManager = accessManager;
            _claimsManager = claimsManager;
        }

        [AllowAnonymous]
        [HttpGet("login")]
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet("denied")]
        [AllowAnonymous]
        public async Task<IActionResult> Denied()
        {
            await HttpContext.SignOutAsync(); return View();
        }

        [HttpPost("login")]
        public async Task<IActionResult> Validate(string Username, string Password)
        {
            var user = await _accessManager.Access(Username, Password);
            if (user != null)
            {
                HttpContext.Session.SetObject(user, "aktifKullanıcı");
                var kullanici = HttpContext.Session.GetObject<Users>("aktifKullanıcı");
                await HttpContext.SignInAsync(await _claimsManager.CreateClaim(kullanici));
                return Redirect("/AdminHome/Index");
            }
            TempData["Error"] = "Hatalı Kullanıcı Adı veya Şifresi";
            return View("Index");
        }
    }
}

MySites/Controllers/SkillsController.cs
using Entities.Entity.Concrete;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Service.Services.Abstract;
using System.Data;

namespace MySites.Controllers
{
    [Authorize(Roles = "Admin")]
    public class SkillsController : Controller
    {
        private readonly ISkillsService _skillsService;

        public SkillsController(ISkillsService skillsService)
        {
            _skillsService = skillsService;
        }
        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> SkillsEkle(Skills skills)
        {
            await _skillsService.CreateAsync(skills);
            return RedirectToAction("Index");
        }
        [HttpPost]
        public async Task<IActionResult> SkillsGuncelle(Skills skills)
        {
            await _skillsService.UpdateAsync(skills);
            return RedirectToAction("Index");
        }
        [HttpPost]
        public async Task<IActionResult> SkillsSil(int id)
        {
            await _skillsService.DeleteAsync(id);
            return RedirectToAction("Index");
        }
        [HttpGet]
        public async Task<IActionResult> SkillsGetAll()
        {
            var skillsData = await _skillsService.GetAllAsync();
            return Json(new { data = skillsData });
        }
    }
}

MySites/Controllers/_LayoutAdminController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace MySites.Controllers
{
    [Authorize(Roles = "Admin")]
    public class _LayoutAdminController : Controller
    {
        public IActionResult _LayoutAdmin()
        {
            return View();
        }
    }
}

MySites/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Start your development with JohnDoe landing page.">
    <meta name="author" content="Devcrud">
    <title>JohnDoe Landing page | Free Bootstrap 4.3.x landing page</title>
    <script src="https://cdn.jsdelivr.net/npm/vue@2.7.10/dist/vue.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <!-- font icons -->
    <link rel="stylesheet" href="/vendors/themify-icons/css/themify-icons.css">

    <!-- Bootstrap + JohnDoe main styles -->
    <link rel="stylesheet" href="/css/johndoe.css">
</head>
<body data-spy="scroll" data-target=".navbar" data-offset="40" id="home">
    <div id="layoutApp">
        <header class="header">
            <div class="container">
                <ul class="social-icons pt-3">
                    <li class="social-item"><a class="social-link text-light" v-bind:href="facebook" target="_blank"><i class="ti-facebook" aria-hidden="true"></i></a></li>
                    <li class="social-item"><a class="social-link text-light" v-bind:href="twitter" target="_blank"><i class="ti-twitter" aria-hidden="true"></i></a></li>
                    <li class="social-item"><a class="social-link text-light" v-bind:href="instagram" target="_blank"><i class="ti-instagram" aria-hidden="true"></i></a></li>
                    <li class="social-item"><a class="social-link text-light" v-bind:href="github" target="_blank"><i class="ti-github" aria-hidden="true"></i></a></li>
                </ul>
                <div class="header-content">
                    <h4 class="header-subtitle">Merhaba, Ben</h4>
                    <h1 class="header-title">Osman Sivrikaya</h1>
                    <h6 class="header-mono">Junior Backend Developer</h6>
                    <button class="btn btn-primary btn-rounded"><i class="ti-printer pr-2"></i>CV</button>
                </div>
            </div>
        </header>
        <nav class="navbar sticky-top navbar-expand-lg navbar-light bg-white" data-spy="affix" data-offset-top="510">
            <div class="container">
                <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse mt-sm-20 navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item">
                            <a href="#home" class="nav-link">Anasayfa</a>
                        </li>
                        <li class="nav-item">
                            <a href="#about" class="nav-link">Hakkımda</a>
                        </li>
                        <li class="nav-item">
                            <a href="#resume" class="nav-link">Özgeçmişim</a>
                        </li>
                    </ul>
                    <ul class="navbar-nav brand">
                        <img src="/imgs/avatar.jpg" alt="" class="brand-img">
                        <li class="brand-txt">
                            <h5 class="brand-title">John Doe</h5>
                            <div class="brand-subtitle">Web Designer | Developer</div>
                        </li>
                    </ul>
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item">
                            <a href="#contact" class="nav-link">Contact</a>
                        </li>
                        <li class="nav-item">
                            <a href="#blog" class="nav-link">Blog</a>
                        </li>
                        <li class="nav-item last-item">
                            <a asp-action="Index" asp-controller="Login" class="nav-link">Login</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </div>
        @RenderBody();
    <div id="footerApp">
        <div class="section contact" id="contact">
            <div id="map" class="map"></div>
            <div class="container">
                <div class="row">
                    <div class="col-lg-8">
                        <div class="contact-form-card">
                            <h4 class="contact-title">Mesaj Gönder</h4>
                            <form action="">
                                <div class="form-group">
                                    <input class="form-control" type="text" placeholder="İsim *" required>
                                </div>
                                <div class="form-group">
                                    <input class="form-control" type="email" placeholder="Email *" required>
                                </div>
                                <div class="form-group">
                                    <textarea class="form-control" id="" placeholder="Mesaj *" rows="7" required></textarea>
                                </div>
                                <div class="form-group ">
                                    <button type="submit" class="form-control btn btn-primary">Mesajı Gönder</button>
                                </div>
                            </form>
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="contact-info-card">
                            <h4 class="contact-title">İletişim Bilgileri</h4>
                            <div class="row mb-2">
                                <div class="col-1 pt-1 mr-1">
                                    <i class="ti-mobile icon-md"></i>
                                </div>
                                <div class="col-10 ">
                                    <h6 class="d-inline">Telefon Numarası : <br> <span class="text-muted">{{phone}}</span></h6>
                                </div>
                            </div>
                            <div class="row mb-2">
                                <div class="col-1 pt-1 mr-1">
                                    <i class="ti-map-alt icon-md"></i>
                                </div>
                                <div class="col-10">
                                    <h6 class="d-inline">Adres :<br> <span class="text-muted">{{address}}</span></h6>
                                </div>
                            </div>
                            <div class="row mb-2">
                                <div class="col-1 pt-1 mr-1">
                                    <i class="ti-envelope icon-md"></i>
                                </div>
                                <div class="col-10">
                                    <h6 class="d-inline">Email :<br> <span class="text-muted">{{email}}</span></h6>
                                </div>
                            </div>
                            <ul class="social-icons pt-4">
                                <li class="social-item"><a class="social-link text-dark" v-bind:href="facebook"><i class="ti-facebook" aria-hidden="true"></i></a></li>
                                <li class="social-item"><a class="social-link text-dark" v-bind:href="twitter"><i class="ti-twitter" aria-hidden="true"></i></a></li>
                                <li class="social-item"><a class="social-link text-dark" v-bind:href="instagram"><i class="ti-instagram" aria-hidden="true"></i></a></li>
                                <li class="social-item"><a class="social-link text-dark" v-bind:href="github"><i class="ti-github" aria-hidden="true"></i></a></li>
                            </ul>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
        <footer class="footer py-3">
            <div class="container">
                <p class="small mb-0 text-light">
                    &copy; <script>document.write(new Date().getFullYear())</script> Created With <i class="ti-heart text-danger"></i> By <a href="http://devcrud.com" target="_blank"><span class="text-danger" title="Bootstrap 4 Themes and Dashboards">DevCRUD</span></a>
                </p>
            </div>
        </footer>
    

    <!-- core  -->
    <script src="/vendors/jquery/jquery-3.4.1.js"></script>
    <script src="/vendors/bootstrap/bootstrap.bundle.js"></script>

    <!-- bootstrap 3 affix -->
    <script src="/vendors/bootstrap/bootstrap.affix.js"></script>

    <!-- Isotope  -->
    <script src="/vendors/isotope/isotope.pkgd.js"></script>

    <!-- Google mpas -->
    <script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCtme10pzgKSPeJVJrG1O3tjR6lk98o4w8&callback=initMap"></script>

    <!-- JohnDoe js -->
    <script src="/js/johndoe.js"></script>
    <script src="/PageEkstra/_Layout.js"></script>

</body>
</html>

MySites/Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>
<html lang="tr">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Admin Panel</title>
    <script src="https://cdn.jsdelivr.net/npm/vue@2.7.10/dist/vue.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <link rel="stylesheet" href="/css/all.min.css">
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="/css/tempusdominus-bootstrap-4.min.css">
    <link rel="stylesheet" href="/css/icheck-bootstrap.min.css">
    <link rel="stylesheet" href="/css/jqvmap.min.css">
    <link rel="stylesheet" href="/css/adminlte.min.css">
    <link rel="stylesheet" href="/css/OverlayScrollbars.min.css">
    <link rel="stylesheet" href="/css/daterangepicker.css">
    <link rel="stylesheet" href="/css/summernote-bs4.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css"
          integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g=="
          crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<body class="hold-transition sidebar-mini layout-fixed">
    <div class="wrapper">

        <!-- Preloader -->
        <div class="preloader flex-column justify-content-center align-items-center">
            <img class="animation__shake" src="/imgs/AdminLTELogo.png" alt="AdminLTELogo" height="60" width="60">
        </div>

        <!-- Navbar Start -->
        <nav class="main-header navbar navbar-expand navbar-white navbar-light">


            <!-- Left navbar links Start -->
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
                </li>
                <li class="nav-item d-none d-sm-inline-block">
                    <a asp-action="Index" asp-controller="AdminHome" class="nav-link">Anasayfa</a>
                </li>
            </ul>
            <!-- Left navbar links End -->
            <!-- Right navbar links Start -->
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" data-widget="fullscreen" href="#" role="button">
                        <i class="fas fa-expand-arrows-alt"></i>
                    </a>
                </li>
            </ul>
            <!-- Right navbar links End -->


        </nav>
        <!--Navbar End -->
        <!-- Main Sidebar Container -->
        <aside class="main-sidebar sidebar-dark-primary elevation-4">
            <!-- Brand Logo -->
            <a asp-action="Index" asp-controller="AdminHome" class="brand-link">
                <img src="/imgs/AdminLTELogo.png" alt="AdminLTE Logo" class="brand-image img-circle " style="opacity: .8">
                <span class="brand-text font-weight-light">Admin Panel</span>
            </a>

            <!-- Sidebar Start -->
            <div class="sidebar">
                <!-- Sidebar user panel (optional) Start -->
                <div class="user-panel mt-3 pb-3 mb-3 d-flex">
                    <div class="image">
                        <img src="/imgs/avatar5.png" class="img-circle elevation-2" alt="User Image">
                    </div>
                    <div class="info">
                        <a href="#" class="d-block">Osman Sivrikaya</a>
                    </div>
                </div>
                <!-- Sidebar user panel (optional) End -->
                <!-- Sidebar Menu Start -->
                <nav class="mt-2">
                    <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                        <!--Kişisel Bilgiler Start-->
                        <li class="nav-item">
                            <a href="#" class="nav-link">
                                <i class="nav-icon fas fa-table"></i>
                                <p>
                                    Kişisel Bilgiler
                                    <i class="fas fa-angle-left right"></i>
                                </p>
                            </a>
                            <ul class="nav nav-treeview">
                                <li class="nav-item">
                                    <a asp-action="Index" asp-controller="PersonelData" class="nav-link">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>Kişisel Bilgiler</p>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="pages/tables/data.html" class="nav-link">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>DataTables</p>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="pages/tables/jsgrid.html" class="nav-link">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>jsGrid</p>
                                    </a>
                                </li>
                            </ul>
                        </li>
                        <!--Kişisel Bilgiler  End-->
                        <!--Özgeçmiş Start-->
                        <li class="nav-item">
                            <a href="#" class="nav-link">
                                <i class="nav-icon fa-solid fa-user-tie"></i>
                                <p>
                                    Özgeçmiş
                                    <i class="fas fa-angle-left right"></i>
                                </p>
                            </a>
                            <ul class="nav nav-treeview">
                                <li class="nav-item">
                                    <a asp-action="Index" asp-controller="Skills" class="nav-link">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>Yetenekler</p>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a asp-action="Index" asp-controller="Languages" class="nav-link">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>Diller</p>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a asp-action="Index" asp-controller="Education" class="nav-link">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>Eğitimler</p>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a asp-action="Index" asp-controller="Experience" class="nav-link">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>Deneyimler</p>
                                    </a>
                                </li>
                            </ul>
                        </li>
                        <!--Froms End-->
                        <!--MailBox Start-->
                        <li class="nav-item">
                            <a href="#" class="nav-link">
                                <i class="nav-icon far fa-envelope"></i>
                                <p>
                                    Mailbox
                                    <i class="fas fa-angle-left right"></i>
                                </p>
                            </a>
                            <ul class="nav nav-treeview">
                                <li class="nav-item">
                                    <a href="pages/mailbox/mailbox.html" class="nav-link">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>Inbox</p>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="pages/mailbox/compose.html" class="nav-link">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>Compose</p>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="pages/mailbox/read-mail.html" class="nav-link">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>Read</p>
                                    </a>
                                </li>
                            </ul>
                        </li>
                        <!--MailBox End-->
                    </ul>
                </nav>
                <!-- Sidebar-menu End -->
            </div>
            <!-- Sidebar End-->
        </aside>

        <div class="content-wrapper">
            <!-- Main content -->
            <section class="content">
                <div class="container-fluid">
                    @RenderBody()
                </div>
            </section>
            <!-- Main content End -->
        </div>


        <!-- Content-wrapper End-->
        <footer class="main-footer">
            <strong>Copyright &copy; 2014-2021 <a href="https://adminlte.io">AdminLTE.io</a>.</strong>
            All rights reserved.
            <div class="float-right d-none d-sm-inline-block">
                <b>Version</b> 3.2.0
            </div>
        </footer>

        <!-- Control Sidebar -->
        <aside class="control-sidebar control-sidebar-dark">
            <!-- Control sidebar content goes here -->
        </aside>
        <!-- /.control-sidebar -->
    </div>
    <script src="/js/jquery-ui.min.js"></script>
    <script>
        $.widget.bridge('uibutton', $.ui.button)
    </script>
    <script src="/js/bootstrap.bundle.min.js"></script>
    <script src="/js/Chart.min.js"></script>
    <script src="/js/sparkline.js"></script>
    
    <script src="/js/moment.min.js"></script>
    <script src="/js/daterangepicker.js"></script>
    <script src="/js/tempusdominus-bootstrap-4.min.js"></script>
    <script src="/js/summernote-bs4.min.js"></script>
    <script src="/js/jquery.overlayScrollbars.min.js"></script>
    <script src="/js/adminlte.js"></script>
    <script src="/js/demo.js"></script>
    <script src="/js/dashboard.js"></script>
</body>
</html>